### ISSUE TITLE
이 프로젝트에서 사용된 모델은 어디서 가져왔습니까?

### ISSUE THREAD

**Issue by boa9448** [updaun/son-eulo#8]
models에 있는 모델은 어디에서 가져온 모델입니까?

**Comment by updaun** [comment]
https://github.com/kinivi/hand-gesture-recognition-mediapipe.git

손가락 좌표의 움직임을 감지하는 모델을 여기서 가져와서 사용중입니다~!
참고하세요!!

나머지는 저희가 만들었네요~ ㅋㅋ 아시겠지만 ㅋ

**Comment by boa9448** [comment]
알려주셔서 감사합니다
